name: Deploy to Cloudflare
on:
  push:
    branches:
      - master
      - staging
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose an environment to deploy to: <staging|prod>'
        required: true
        default: 'staging'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install --production=false

      - name: Build and publish project
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: publish --env ${{ github.ref_name }} --var COMMIT:${{ github.sha }}